services:
  api: 
    container_name: veiculos-api
    build:
      dockerfile: Veiculos.Web/Dockerfile
      context: .
    ports:
      - 4652:8080
    environment:
     - "ASPNETCORE_ENVIRONMENT=Development"
    depends_on: ["veiculos-db"]
    networks:
      veiculos-network:

  veiculos-db:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=VeiculosDB123"
      - "MSSQL_PID=Evaluation"
    volumes:
      - "veiculos-db-volume:/var/opt/mssql"
    networks:
      veiculos-network:
        aliases:
          - "sql"

volumes:
    veiculos-db-volume:

networks:
  veiculos-network:
    driver: bridge
        